-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.InputObject exposing (..)

import Api.Interface
import Api.Object
import Api.Scalar
import Api.ScalarCodecs
import Api.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


buildDemoInputInput :
    DemoInputInputRequiredFields
    -> DemoInputInput
buildDemoInputInput required____ =
    { int = required____.int }


type alias DemoInputInputRequiredFields =
    { int : Int }


{-| Type for the DemoInputInput input object.
-}
type alias DemoInputInput =
    { int : Int }


{-| Encode a DemoInputInput into a value that can be used as an argument.
-}
encodeDemoInputInput : DemoInputInput -> Value
encodeDemoInputInput input____ =
    Encode.maybeObject
        [ ( "int", Encode.int input____.int |> Just ) ]
