name: Backend - compile, check, codegen

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      # "synchronize" means new commits pushed to the HEAD of the pull request branch
      - synchronize

permissions: read-all

jobs:
  cancel-previous:
    runs-on: ubuntu-22.04
    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.11.0

  build:
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: backend

    steps:
      - uses: actions/checkout@v3

      - name: Setup scala
        uses: olafurpg/setup-scala@v13
        with:
          java-version: amazon-corretto@1.11

      - name: Compile, check formatting, lint, and run tests
        run: sbt compile styleCheck test

      - name: Generate GraphQL Schema
        run: sbt generateGqlSchema

      - name: Get files changed after schema generation
        id: changed-schema-files
        uses: tj-actions/changed-files@v35
        with:
          files: graphql-schema/**

      - name: Fail if GraphQL schema is not up-to-date
        if: steps.changed-schema-files.outputs.any_changed == 'true'
        run: |
          echo "GraphQL schema is not up-to-date. Did you forget to run `sbt generateGqlSchema`?"
          exit 1
